In [213]:
import numpy as np

In [214]:
arr1d = np.array([1, 2, 3])
display(arr1d)

array([1, 2, 3])

In [215]:
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
display(arr2d)

array([[1, 2, 3],
       [4, 5, 6]])

In [216]:
arr3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
    ],
    [
        [9, 8, 7],
        [6, 5, 4],
    ]
])
display(arr3d)

array([[[1, 2, 3],
        [4, 5, 6]],

       [[9, 8, 7],
        [6, 5, 4]]])

In [217]:
arr2d.shape

(2, 3)

In [218]:
arr2d.ndim

2

In [219]:
arr2d.size

6

In [220]:
arr2d.dtype

dtype('int64')

In [221]:
arr2d.itemsize

8

In [222]:
floatArr = np.array([1, 2, 3], dtype=float)

In [223]:
floatArr.dtype

dtype('float64')

In [224]:
zeroArr = np.zeros((2, 3), dtype=int)

In [225]:
display(zeroArr)

array([[0, 0, 0],
       [0, 0, 0]])

In [226]:
rangeArray = np.arange(10, 22)
rangeArray.reshape((4, 3))

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [227]:
display(rangeArray)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [228]:
rangeArray[2:7]

array([12, 13, 14, 15, 16])

In [229]:
rangeArray[6:1:-1]

array([16, 15, 14, 13, 12])

In [230]:
marks = np.array([
    [78, 67, 56],
    [76, 75, 47],
    [84, 59, 60],
    [67, 72, 54]
])

In [231]:
marks.sort()

In [232]:
print(marks)

[[56 67 78]
 [47 75 76]
 [59 60 84]
 [54 67 72]]


In [233]:
marks[1:3,1:]

array([[75, 76],
       [60, 84]])

In [234]:
arr1 = np.array([
    [10, 20],
    [-30, 40]
], dtype=int)

arr2 = np.zeros((2, 3), dtype=int)

In [235]:
np.concatenate((arr1, arr2), axis=1)

array([[ 10,  20,   0,   0,   0],
       [-30,  40,   0,   0,   0]])

In [236]:
matrix = np.array([
    [10, -7, 0, 20],
    [5, 1, 200, 40],
    [6, 9, 39, 1],
    [67, 25, 36, 93],
    [2, 3, -7, 0]
], dtype=int)

In [237]:
first, second, third = np.split(matrix, [2, 3], axis=1)

In [238]:
display(first)
display(second)
display(third)

array([[10, -7],
       [ 5,  1],
       [ 6,  9],
       [67, 25],
       [ 2,  3]])

array([[  0],
       [200],
       [ 39],
       [ 36],
       [ -7]])

array([[20],
       [40],
       [ 1],
       [93],
       [ 0]])

In [239]:
# a, b = np.loadtxt("data.txt", dtype=int, delimiter=",", skiprows=1)[:, 1:]

In [240]:
np.genfromtxt("data.txt", dtype=int, delimiter=",", skip_header=True, filling_values=-9999)

array([[    1,    12,    20,    30],
       [    2,    16, -9999,    18]])

In [242]:
display(matrix)

array([[ 10,  -7,   0,  20],
       [  5,   1, 200,  40],
       [  6,   9,  39,   1],
       [ 67,  25,  36,  93],
       [  2,   3,  -7,   0]])

In [245]:
np.savetxt("matrix.txt", matrix, "%4d")